build:
	gcc -Wall -Wextra -pedantic -std=c11 head.c -o head
	gcc -Wall -Wextra -pedantic -std=c11 task2.c -o task2
	gcc -Wall -Wextra -pedantic -std=c11 task3.c -o task3

head: head.c
	gcc -Wall -Wextra -pedantic -std=c11 head.c -o head

task2: task2.c
	gcc -Wall -Wextra -pedantic -std=c11 task2.c -o task2

task3: task3.c
	gcc -Wall -Wextra -pedantic -std=c11 task3.c -o task3